export const affirmations = [
	'Keep up the great work! 🌟',
	"You're doing amazing! 🚀",
	'Keep on rocking! 🎸',
	'Stay awesome! 😎',
	'Keep shining bright! 💡',
	"You've got this! 💪",
	'Onwards and upwards! 🌈',
	'You are a star! 🌟',
	'Fantastic job! 👍',
	'Brilliant work! 🔥',
	"You're a wizard, Harry! 🧙‍♂️",
	'Keep making magic! 🧙‍♂️',
	"You're a champ! 🏆",
	'Stay brilliant! 💎',
	'Top-notch work! 🥇',
	'Absolutely fabulous! 💃',
	"I'd give you an A+! 🥇",
	'Slay Queen! 👑',
	'Stay fabulous! 💅',
	"You're unstoppable! 🌪️",
	'Keep conquering! 🏰',
	'Keep on shining! ✨',
	'Go for gold! 🥇',
];
